import Head from "next/head";
import ContactUs from "./components/contactUs";
import NavbarIndex from "./components/navbarIndex";
import Outro from "./components/outro";

export default function Home() {
  return (
    <>
      <Head>
        <title>PT Salamun Teknologi Indonesia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Mulish:wght@500&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        {/* Navbar */}
        <NavbarIndex />
        {/* Tutup Navbar */}

        {/* Intro */}
        <section id="intro" className="mt-[125px] md:mt-[183px] mx-auto">
          <div>
            <h1 className="ml-8 text-xl tracking-wider md:text-3xl md:tracking-wide md:ml-10 md:mt-[-25px] md:ml-28 lg:ml-[139px] md:tracking-widest lg:mt-0 lg:leading-[50px] lg:text-4xl font-semibold">
              A Software House <br />
              Specializing in Application <br />
              Development
            </h1>
            <div className=" flex">
              <ContactUs />
            </div>
          </div>
        </section>
        {/* Tutup Intro */}

        {/* Service */}
        <section id="service">
          <h1 className=" text-3xl pt-[8rem] text-blue-300 text-center">
            What We Do?
          </h1>
          <p className=" text-gray-50 pt-3 text-center">
            The service we offer is specifically <br /> designed to meet your
            <br />
            requirements.
          </p>
          <div className="bg-transparent grid grid-rows-4 md:grid-rows-4 lg:grid-rows-4 xl:grid-rows-2 mt-28 grid-flow-col">
            <div className="bg-transparent overflow-hidden mx-auto md:mx-auto lg:mx-auto xl:ml-36 text-gray-50 xl:mt-[-4rem]">
              <img
                className=" mb-[-5rem] w-24 ml-10 md:w-48 md:ml-[5rem] md:mb-[-6rem]"
                src="/i24.png"
                alt="webdev"
              />
              <div className=" shadow2 px-3 py-2 m-12 w-[212px] mb-[14px] mr-2 md:px-6 md:py-4 bg-biru md:ml-24 md:w-[424px] md:mb-7 md:mr-4 rounded-2xl">
                <div className=" mt-8 pl-8 md:mt-24 md:pl-16">
                  <div className="text-xl text-blue-300 mb-2">
                    Web Development
                  </div>
                  <p className="text-xs md:text-base">
                    We help you to Develop application for your business, both
                    vertical (industry specific) and horizontal (serve a
                    particular need across all organizations and industries).
                  </p>
                </div>
              </div>
            </div>
            <div className="bg-transparent overflow-hidden mx-auto md:mx-auto lg:mx-auto xl:ml-36 text-gray-50 xl:mt-[-4rem]">
              <img
                className="mb-[-5rem] w-24 ml-10 md:mb-[-6rem] md:w-48 md:ml-[5rem]"
                src="/i23.png"
                alt="webdev"
              />
              <div className=" shadow2 px-3 py-2 m-12 w-[212px] mb-[14px] mr-2 md:px-6 md:py-4 bg-biru md:ml-24 md:w-[424px] md:mb-7 md:mr-4 rounded-2xl">
                <div className="mt-8 pl-8 md:mt-24 md:pl-16">
                  <div className="text-xl text-blue-300 mb-2">
                    Managed Server
                  </div>
                  <p className="text-xs md:text-base">
                    We can manage your domain and application servers from
                    registration, renewal, configuration settings and other
                    related matters including integrating software into
                    business.
                  </p>
                </div>
              </div>
            </div>
            <div className="bg-transparent overflow-hidden mx-auto md:mx-auto lg:mx-auto xl:mr-36 text-gray-50 xl:mt-[-4rem] xl:mt-24">
              <img
                className="mb-[-5rem] w-24 ml-10 md:mb-[-6rem] md:w-48 md:ml-[5rem]"
                src="/i22.png"
                alt="webdev"
              />
              <div className=" shadow2 px-3 py-2 m-12 w-[212px] mb-[14px] mr-2 md:px-6 md:py-4 bg-biru md:ml-24 md:w-[424px] md:mb-7 md:mr-4 rounded-2xl">
                <div className=" mt-8 pl-8 md:mt-24 md:pl-16">
                  <div className="text-xl text-blue-300 mb-2">
                    Desktop Development
                  </div>
                  <p className="text-xs md:text-base">
                    Is there a technology-based product that you want to
                    develop? Trust us to develop it with an end-to-end solution
                    from the design process to its implementation.
                  </p>
                </div>
              </div>
            </div>
            <div className="bg-transparent overflow-hidden mx-auto md:mx-auto lg:mx-auto xl:mr-36 text-gray-50 xl:mt-[-4rem] xl:mt-24">
              <img
                className="mb-[-5rem] w-24 ml-10 md:mb-[-6rem] md:w-48 md:ml-[5rem]"
                src="/i26.png"
                alt="webdev"
              />
              <div className=" shadow2 px-3 py-2 m-12 w-[212px] mb-[14px] mr-2 md:px-6 md:py-4 bg-biru md:ml-24 md:w-[424px] md:mb-7 md:mr-4 rounded-2xl">
                <div className="mt-8 pl-8 md:mt-24 md:pl-16">
                  <div className="text-xl text-blue-300 mb-2">
                    Mobile App Development
                  </div>
                  <p className="text-xs md:text-base">
                    In today's market, every company needs an effective website.
                    Likewise with mobile-based applications that will help
                    improve your company's image.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* Tutup Service */}

        {/* Teams */}
        <section>
          <div id="teams">
            <div className="text-center">
              <h1 className="md:text-3xl text-sm pt-[8rem] font-semibold text-blue-300">
                We Are Proud of Our Team
              </h1>
              <br />
              <p className="text-sm md:text-base text-gray-600 font-semibold">
                Just sit back and relax while we take care of <br /> your
                business needs for you.
              </p>
              <br />
              <br />

              <div className=" xl:mx-52 md:mx-24">
                <div className="grid xl:grid-cols-4 lg:grid-cols-4 md:grid-cols-4 grid-cols-2 gap-0 flex justify-items-center">
                  <div className="w-[106px] h-[165px] lg:w-[200px] lg:h-[330px] rounded overflow-hidden shadow3">
                    <img
                      className=" w-[87px] lg:w-[164px] mx-auto my-[6px] lg:my-3"
                      src="kangFaerul.png"
                      alt="Sunset in the mountains"
                    />
                    <div className="px-1 py-1 lg:px-6 lg:py-4">
                      <div className="font-bold text-[12px] lg:text-xl lg:mb-2">
                        Faerul Salamun
                      </div>
                      <h1 className="text-gray-400 text-sm font-semibold lg:text-base">
                        CEO
                      </h1>
                      <div className="px-5 pt-1 lg:px-6 lg:pt-3 gap-x-2 flex pb-2">
                        <a href="">
                          <img
                            className="w-[15px]"
                            src="icon/ico-linkedin.svg"
                            alt=""
                          />
                        </a>
                        <a href="" className="w-[15px]">
                          <img src="icon/ico-github.svg" alt="" />
                        </a>
                        <a href="" className="w-[15px]">
                          <img src="icon/ico-youtube.svg" alt="" />
                        </a>
                      </div>
                    </div>
                  </div>
                  <div className="w-[106px] h-[165px] lg:w-[200px] lg:h-[330px] rounded overflow-hidden shadow3">
                    <img
                      className=" w-[87px] lg:w-[164px] mx-auto my-[6px] lg:my-3"
                      src="kangFaerul.png"
                      alt="Sunset in the mountains"
                    />
                    <div className="px-1 py-1 lg:px-6 lg:py-4">
                      <div className="font-bold text-[12px] lg:text-xl lg:mb-2">
                        Faerul Salamun
                      </div>
                      <h1 className="text-gray-400 text-sm font-semibold lg:text-base">
                        CEO
                      </h1>
                      <div className="px-5 pt-1 lg:px-6 lg:pt-3 gap-x-2 flex pb-2">
                        <a href="">
                          <img
                            className="w-[15px]"
                            src="icon/ico-linkedin.svg"
                            alt=""
                          />
                        </a>
                        <a href="" className="w-[15px]">
                          <img src="icon/ico-github.svg" alt="" />
                        </a>
                        <a href="" className="w-[15px]">
                          <img src="icon/ico-youtube.svg" alt="" />
                        </a>
                      </div>
                    </div>
                  </div>
                  <div className="w-[106px] h-[165px] lg:w-[200px] lg:h-[330px] mt-8 md:mt-0 rounded overflow-hidden shadow3">
                    <img
                      className=" w-[87px] lg:w-[164px] mx-auto my-[6px] lg:my-3"
                      src="kangFaerul.png"
                      alt="Sunset in the mountains"
                    />
                    <div className="px-1 py-1 lg:px-6 lg:py-4">
                      <div className="font-bold text-[12px] lg:text-xl lg:mb-2">
                        Faerul Salamun
                      </div>
                      <h1 className="text-gray-400 text-sm font-semibold lg:text-base">
                        CEO
                      </h1>
                      <div className="px-5 pt-1 lg:px-6 lg:pt-3 gap-x-2 flex pb-2">
                        <a href="">
                          <img
                            className="w-[15px]"
                            src="icon/ico-linkedin.svg"
                            alt=""
                          />
                        </a>
                        <a href="" className="w-[15px]">
                          <img src="icon/ico-github.svg" alt="" />
                        </a>
                        <a href="" className="w-[15px]">
                          <img src="icon/ico-youtube.svg" alt="" />
                        </a>
                      </div>
                    </div>
                  </div>
                  <div className="w-[106px] h-[165px] lg:w-[200px] lg:h-[330px] mt-8 md:mt-0 rounded overflow-hidden shadow3">
                    <img
                      className=" w-[87px] lg:w-[164px] mx-auto my-[6px] lg:my-3"
                      src="kangFaerul.png"
                      alt="Sunset in the mountains"
                    />
                    <div className="px-1 py-1 lg:px-6 lg:py-4">
                      <div className="font-bold text-[12px] lg:text-xl lg:mb-2">
                        Faerul Salamun
                      </div>
                      <h1 className="text-gray-400 text-sm font-semibold lg:text-base">
                        CEO
                      </h1>
                      <div className="px-5 pt-1 lg:px-6 lg:pt-3 gap-x-2 flex pb-2">
                        <a href="">
                          <img
                            className="w-[15px]"
                            src="icon/ico-linkedin.svg"
                            alt=""
                          />
                        </a>
                        <a href="" className="w-[15px]">
                          <img src="icon/ico-github.svg" alt="" />
                        </a>
                        <a href="" className="w-[15px]">
                          <img src="icon/ico-youtube.svg" alt="" />
                        </a>
                      </div>
                    </div>
                  </div>

                  <br />
                  <br />
                  <br />
                </div>
              </div>
            </div>
          </div>
        </section>
        {/* Tutup Teams */}

        {/* Tech */}
        <section>
          <div id="techstack">
            <h1 className=" uppercase text-center text-sm md:text-xl lg:text-3xl mb-6 pt-[8rem] font-bold text-blue-300">
              Tech Stack
            </h1>
            <div className="grid grid-flow-col auto-cols-max items-center justify-center gap-x-[11px]">
              <div>
                <img
                  className="w-[63px] md:w-[103px] lg:w-full h-auto"
                  src="tech/26.png"
                  alt=""
                />
              </div>
              <div>
                <img
                  className="w-[63px] md:w-[103px] lg:w-full h-auto"
                  src="tech/27.png"
                  alt=""
                />
              </div>
              <div>
                <img
                  className="w-[50px] md:w-[90px] lg:w-full h-auto"
                  src="tech/28.png"
                  alt=""
                />
              </div>
              <div>
                <img
                  className="w-[35px] md:w-[75px] lg:w-full h-auto"
                  src="tech/29.png"
                  alt=""
                />
              </div>
              <div>
                <img
                  className="w-[22px] md:w-[62px] lg:w-full h-auto"
                  src="tech/30.png"
                  alt=""
                />
              </div>
            </div>
            <div className="grid grid-flow-col auto-cols-max items-center justify-center gap-x-[11px] md:gap-x-11">
              <div>
                <img
                  className="w-[63px] md:w-[103px] lg:w-full h-auto"
                  src="tech/33.png"
                  alt=""
                />
              </div>
              <div>
                <img
                  className="w-[32px] md:w-[52px] lg:w-full h-auto"
                  src="tech/34.png"
                  alt=""
                />
              </div>
              <div>
                <img
                  className="w-[62px] md:w-[82px] lg:w-full h-auto"
                  src="tech/35.png"
                  alt=""
                />
              </div>
              <div>
                <img
                  className="w-[62px] md:w-[82px] lg:w-full h-auto"
                  src="tech/36.png"
                  alt=""
                />
              </div>
            </div>
            <div className="grid grid-flow-col auto-cols-max items-center justify-center gap-x-[4px] md:gap-x-10">
              <div>
                <img
                  className="w-[62px] md:w-[82px] lg:w-full h-auto"
                  src="tech/31.png"
                  alt=""
                />
              </div>
              <div>
                <img
                  className="w-[62px] md:w-[82px] lg:w-full h-auto"
                  src="tech/32.png"
                  alt=""
                />
              </div>
              <div>
                <img
                  className="w-[63px] md:w-[83px] lg:w-full h-auto"
                  src="tech/37.png"
                  alt=""
                />
              </div>
              <div>
                <img
                  className="w-[38px] lg:w-full h-auto ml-7"
                  src="tech/38.png"
                  alt=""
                />
              </div>
            </div>
          </div>
        </section>
        {/* Tutup Tech */}

        {/* Maps */}
        <section className="mt-28 ">
          <div className="pt-[13px] pb-[13px] px-[10px] md:px-9 md:pt-[19px] lg:pt-10 lg:pb-10 lg:px-10 shadow3 lg:w-[861px] mx-auto">
            <div className="w-auto h-auto mx-auto md:w-[700px] md:h-[330px]">
              <iframe
                className="w-auto h-auto md:h-[328px] md:w-[678px] mx-auto"
                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3960.498424594971!2d107.64474461546196!3d-6.95038076997705!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x2e68dd950cc15259%3A0xf5a14138db1906d6!2sPT%20Salamun%20Teknologi%20Indonesia!5e0!3m2!1sid!2sid!4v1664611387561!5m2!1sid!2sid"
              ></iframe>
            </div>
          </div>
          <br />
          <br />
          <br />
          <br />
          <br />
        </section>
        {/* Tutup Maps */}

        {/* Outro */}
        <Outro />
        {/* Tutup Outro */}

        {/* Footer */}

        {/* Tutup Footer */}
      </main>
    </>
  );
}
